# Generated by Django 3.2.9 on 2021-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_username', models.CharField(max_length=200)),
                ('task_title', models.CharField(max_length=200)),
                ('task_desc', models.CharField(max_length=200)),
                ('task_condition', models.IntegerField()),
                ('task_assigned', models.IntegerField()),
            ],
        ),
    ]
